### ISSUE TITLE
Assembly.Load On unsafe assembly

### ISSUE THREAD

**Issue by wineggdrop** [zcgonvh/DCOMPotato#2]
it always catchs BadImageFormatException,not sure why."An attempt was made to load a program with an incorrect format"

**Comment by zcgonvh** [comment]
ensure the loader process is 64 bit, wow64 or 32 bit process not supported currently .

**Comment by wineggdrop** [comment]
I am sure it's not about the architecture issue becuase I have tried the x86/x64/Any cpu loader,all the same error.However,using Assembly.LoadFrom works fine.
